version: "3.8"

services:
  
  api:
    image: openai-test-dev
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:12
    env_file: .env
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data:
